### ISSUE TITLE
Topluluk detay sayfası

### ISSUE THREAD

**Issue by saracalihan** [mavidurak/orientation-front-end#12]
## Görev Tanımı
Topluluğun afiş, isim, sahib(ler)i, detayı, postlar gibi bilgilerinin gösterileceği sayfa hazırlanmalı

### Komponetler ve View'lar 
+ View
  + `CommunityDetail`:  path: `/communities` toplulukların listeleneceği sayfa

## Dosya Yapısı
```
   ...
    ├── views
    │   ├── ...
    │   └── CommunityDetail.vue
   ...
```
### Veriler
```
community: {
  id: number,
  name: string,
  image: string, // image url
  members: number,
  category: string,
  tags: [string],
  rules: string,
  createdAt: date,
  updatedAt: date,
}
```

## Örnek
![image](https://user-images.githubusercontent.com/56413673/113513362-08b7b680-9572-11eb-9a2d-27506d6bd55c.png)
En allta bulunan `Discussion Board` kısmına `Posts` yazılmalı ve içeriği boş bırakılmalı

[Demo için tıklayın](https://www.goodreads.com/group/show/220-goodreads-librarians-group)

**Comment by saracalihan** [comment]
@Arifkarakilic

**Comment by Arifkarakilic** [comment]
fe için geri dönüldüğünde issue tekrar açılıp tamamlanacaktır.

**Comment by saracalihan** [comment]
> fe için geri dönüldüğünde issue tekrar açılıp tamamlanacaktır.

İsteğiniz **reddedildi**.En kısa sürede durumunuz hakkında yazılı bilgi veriniz ve gerekli işlemleri yapınız.
