### ISSUE TITLE
404 Not Found Page

### ISSUE THREAD

**Issue by beyzaerkan** [mavidurak/orientation-front-end#46]
Aşağıda bulunan **404 sayfası** tasarımlarından en beğendiğinize "👍" emojisi koyarak oylamaya katılabilirisiniz.

**Comment by saracalihan** [comment]
https://user-images.githubusercontent.com/76122007/128498831-5474c458-e030-4285-94d7-4f21c5821ddc.png

**Comment by saracalihan** [comment]
!["404"](https://user-images.githubusercontent.com/76122007/128498840-e30c5433-9b01-4732-bfda-ef098c1f5ffc.png)

**Comment by saracalihan** [comment]
!["404"](https://user-images.githubusercontent.com/76122007/128498846-265bb053-8504-43a0-b150-f395f2495d12.png)

**Comment by saracalihan** [comment]
!["404"](https://user-images.githubusercontent.com/76122007/128498854-f789e50d-72bc-4367-95a2-dafc84ae8e05.png)

**Comment by beyzaerkan** [comment]
![Screenshot from 2021-08-09 21-18-55](https://user-images.githubusercontent.com/76122007/128762629-e85bb4d5-9dde-478c-9472-22a66cd3d958.png)

**Comment by beyzaerkan** [comment]
![Screenshot from 2021-08-09 21-29-27](https://user-images.githubusercontent.com/76122007/128762663-3adc5dfa-c691-4e63-a105-c573a0b8c20c.png)

**Comment by beyzaerkan** [comment]
![Screenshot from 2021-08-09 22-15-22](https://user-images.githubusercontent.com/76122007/128762709-fd0787a4-bcca-46ff-8c6b-cf94078d67cf.png)

**Comment by beyzaerkan** [comment]
![Screenshot from 2021-08-09 22-20-59](https://user-images.githubusercontent.com/76122007/128762734-cc13a3c2-1084-4d49-b1fc-97b1e9c8d44c.png)
